server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/useraccount
    username: root
    password: Pr@gm4

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: user-microservice

appDescription: "Pragma User"
appVersion: "1.0.0"
